# Generated by Django 3.1 on 2020-08-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('apellido', models.CharField(default='', max_length=200)),
                ('edad', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('cedula', models.CharField(default='', max_length=10)),
                ('curso_asignado', models.CharField(default='', max_length=15)),
                ('materias', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
